/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainSubgroupsRouteImport } from './routes/_main.subgroups'
import { Route as MainSpecializationsRouteImport } from './routes/_main.specializations'
import { Route as MainReportsRouteImport } from './routes/_main.reports'
import { Route as MainNotesRouteImport } from './routes/_main.notes'
import { Route as MainMidtermExamTypesRouteImport } from './routes/_main.midtermExamTypes'
import { Route as MainMidtermExamRouteImport } from './routes/_main.midtermExam'
import { Route as MainJournalRouteImport } from './routes/_main.journal'
import { Route as MainGroupJournalRouteImport } from './routes/_main.groupJournal'
import { Route as MainGroupConsultRouteImport } from './routes/_main.groupConsult'
import { Route as MainDataRouteImport } from './routes/_main.data'
import { Route as MainConsultRouteImport } from './routes/_main.consult'
import { Route as MainCompensationRouteImport } from './routes/_main.compensation'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSubgroupsRoute = MainSubgroupsRouteImport.update({
  id: '/subgroups',
  path: '/subgroups',
  getParentRoute: () => MainRoute,
} as any)
const MainSpecializationsRoute = MainSpecializationsRouteImport.update({
  id: '/specializations',
  path: '/specializations',
  getParentRoute: () => MainRoute,
} as any)
const MainReportsRoute = MainReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MainRoute,
} as any)
const MainNotesRoute = MainNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => MainRoute,
} as any)
const MainMidtermExamTypesRoute = MainMidtermExamTypesRouteImport.update({
  id: '/midtermExamTypes',
  path: '/midtermExamTypes',
  getParentRoute: () => MainRoute,
} as any)
const MainMidtermExamRoute = MainMidtermExamRouteImport.update({
  id: '/midtermExam',
  path: '/midtermExam',
  getParentRoute: () => MainRoute,
} as any)
const MainJournalRoute = MainJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => MainRoute,
} as any)
const MainGroupJournalRoute = MainGroupJournalRouteImport.update({
  id: '/groupJournal',
  path: '/groupJournal',
  getParentRoute: () => MainRoute,
} as any)
const MainGroupConsultRoute = MainGroupConsultRouteImport.update({
  id: '/groupConsult',
  path: '/groupConsult',
  getParentRoute: () => MainRoute,
} as any)
const MainDataRoute = MainDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => MainRoute,
} as any)
const MainConsultRoute = MainConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => MainRoute,
} as any)
const MainCompensationRoute = MainCompensationRouteImport.update({
  id: '/compensation',
  path: '/compensation',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/compensation': typeof MainCompensationRoute
  '/consult': typeof MainConsultRoute
  '/data': typeof MainDataRoute
  '/groupConsult': typeof MainGroupConsultRoute
  '/groupJournal': typeof MainGroupJournalRoute
  '/journal': typeof MainJournalRoute
  '/midtermExam': typeof MainMidtermExamRoute
  '/midtermExamTypes': typeof MainMidtermExamTypesRoute
  '/notes': typeof MainNotesRoute
  '/reports': typeof MainReportsRoute
  '/specializations': typeof MainSpecializationsRoute
  '/subgroups': typeof MainSubgroupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/compensation': typeof MainCompensationRoute
  '/consult': typeof MainConsultRoute
  '/data': typeof MainDataRoute
  '/groupConsult': typeof MainGroupConsultRoute
  '/groupJournal': typeof MainGroupJournalRoute
  '/journal': typeof MainJournalRoute
  '/midtermExam': typeof MainMidtermExamRoute
  '/midtermExamTypes': typeof MainMidtermExamTypesRoute
  '/notes': typeof MainNotesRoute
  '/reports': typeof MainReportsRoute
  '/specializations': typeof MainSpecializationsRoute
  '/subgroups': typeof MainSubgroupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/_main/compensation': typeof MainCompensationRoute
  '/_main/consult': typeof MainConsultRoute
  '/_main/data': typeof MainDataRoute
  '/_main/groupConsult': typeof MainGroupConsultRoute
  '/_main/groupJournal': typeof MainGroupJournalRoute
  '/_main/journal': typeof MainJournalRoute
  '/_main/midtermExam': typeof MainMidtermExamRoute
  '/_main/midtermExamTypes': typeof MainMidtermExamTypesRoute
  '/_main/notes': typeof MainNotesRoute
  '/_main/reports': typeof MainReportsRoute
  '/_main/specializations': typeof MainSpecializationsRoute
  '/_main/subgroups': typeof MainSubgroupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/compensation'
    | '/consult'
    | '/data'
    | '/groupConsult'
    | '/groupJournal'
    | '/journal'
    | '/midtermExam'
    | '/midtermExamTypes'
    | '/notes'
    | '/reports'
    | '/specializations'
    | '/subgroups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/compensation'
    | '/consult'
    | '/data'
    | '/groupConsult'
    | '/groupJournal'
    | '/journal'
    | '/midtermExam'
    | '/midtermExamTypes'
    | '/notes'
    | '/reports'
    | '/specializations'
    | '/subgroups'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/forbidden'
    | '/login'
    | '/_main/compensation'
    | '/_main/consult'
    | '/_main/data'
    | '/_main/groupConsult'
    | '/_main/groupJournal'
    | '/_main/journal'
    | '/_main/midtermExam'
    | '/_main/midtermExamTypes'
    | '/_main/notes'
    | '/_main/reports'
    | '/_main/specializations'
    | '/_main/subgroups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/subgroups': {
      id: '/_main/subgroups'
      path: '/subgroups'
      fullPath: '/subgroups'
      preLoaderRoute: typeof MainSubgroupsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/specializations': {
      id: '/_main/specializations'
      path: '/specializations'
      fullPath: '/specializations'
      preLoaderRoute: typeof MainSpecializationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/reports': {
      id: '/_main/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof MainReportsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/notes': {
      id: '/_main/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof MainNotesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/midtermExamTypes': {
      id: '/_main/midtermExamTypes'
      path: '/midtermExamTypes'
      fullPath: '/midtermExamTypes'
      preLoaderRoute: typeof MainMidtermExamTypesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/midtermExam': {
      id: '/_main/midtermExam'
      path: '/midtermExam'
      fullPath: '/midtermExam'
      preLoaderRoute: typeof MainMidtermExamRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/journal': {
      id: '/_main/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof MainJournalRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/groupJournal': {
      id: '/_main/groupJournal'
      path: '/groupJournal'
      fullPath: '/groupJournal'
      preLoaderRoute: typeof MainGroupJournalRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/groupConsult': {
      id: '/_main/groupConsult'
      path: '/groupConsult'
      fullPath: '/groupConsult'
      preLoaderRoute: typeof MainGroupConsultRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/data': {
      id: '/_main/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof MainDataRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/consult': {
      id: '/_main/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof MainConsultRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/compensation': {
      id: '/_main/compensation'
      path: '/compensation'
      fullPath: '/compensation'
      preLoaderRoute: typeof MainCompensationRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainCompensationRoute: typeof MainCompensationRoute
  MainConsultRoute: typeof MainConsultRoute
  MainDataRoute: typeof MainDataRoute
  MainGroupConsultRoute: typeof MainGroupConsultRoute
  MainGroupJournalRoute: typeof MainGroupJournalRoute
  MainJournalRoute: typeof MainJournalRoute
  MainMidtermExamRoute: typeof MainMidtermExamRoute
  MainMidtermExamTypesRoute: typeof MainMidtermExamTypesRoute
  MainNotesRoute: typeof MainNotesRoute
  MainReportsRoute: typeof MainReportsRoute
  MainSpecializationsRoute: typeof MainSpecializationsRoute
  MainSubgroupsRoute: typeof MainSubgroupsRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCompensationRoute: MainCompensationRoute,
  MainConsultRoute: MainConsultRoute,
  MainDataRoute: MainDataRoute,
  MainGroupConsultRoute: MainGroupConsultRoute,
  MainGroupJournalRoute: MainGroupJournalRoute,
  MainJournalRoute: MainJournalRoute,
  MainMidtermExamRoute: MainMidtermExamRoute,
  MainMidtermExamTypesRoute: MainMidtermExamTypesRoute,
  MainNotesRoute: MainNotesRoute,
  MainReportsRoute: MainReportsRoute,
  MainSpecializationsRoute: MainSpecializationsRoute,
  MainSubgroupsRoute: MainSubgroupsRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
